# Generated by Django 6.0.1 on 2026-04-11 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_index', models.PositiveIntegerField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('already_used', 'Already Used'), ('outdated', 'Outdated QR'), ('invalid', 'Invalid QR')], default='invalid', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='bookings.booking')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Scanned By')),
            ],
            options={
                'verbose_name': 'Ticket Scan Log',
                'verbose_name_plural': 'Ticket Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
