# Generated by Django 6.0.1 on 2026-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ticketscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='latest_qr_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('USED', 'Used')], default='PENDING', max_length=20),
        ),
    ]
