# Generated by Django 6.0.1 on 2026-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_checkout_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkout_request_id',
            new_name='payment_reference',
        ),
        migrations.AddField(
            model_name='booking',
            name='attendee_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
