# Generated by Django 6.0.1 on 2026-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_checkout_request_id_booking_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='validation_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
