# Generated by Django 6.0.1 on 2026-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_validation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='validation_token',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='scan_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
