# Generated by Django 6.0.1 on 2026-03-30 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_promocode'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={},
        ),
        migrations.AddField(
            model_name='promocode',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='events.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_promos', to=settings.AUTH_USER_MODEL),
        ),
    ]
